### ISSUE TITLE
Compatibility problem w/Grails 3.0.15

### ISSUE THREAD

**Issue by sbortman** [appcela/grails3-cors-interceptor#2]
When upgrading from Grails 3.0.14 to 3.0.15,  encountered a stacktrace and prevented the application from starting:

PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'grailsApplication' threw exception; nested exception is java.lang.AbstractMethodError: grails3.cors.interceptor.CorsInterceptor.setGrailsApplication(Lgrails/core/GrailsApplication;)V

Downloading the source for 0.12 and running as inline plugin seems to work.   Graeme and Jeff Scott Brown suggested that the plugin needs to be compiled w/a newer version grails due to a binary compatibility issue.

**Comment by ichangxappcela** [comment]
Yeah, 3.1.2 also came out. I'll take a look at both versions over the weekend.

**Comment by ichangxappcela** [comment]
@sbortman , just released v0.1.3 (recompiled with Grails 3.0.15). Please give it a try and let me know how it works.

**Comment by sbortman** [comment]
Hello,

Thanks again for taking a look at it.  Still having issues.   I looked at your changes and I wonder if you need to bump up the grails version in gradle.properties  and commit that as well?

Take care,
--scottie

**Comment by ichangxappcela** [comment]
@sbortman , yup, that was it!

New version 0.1.4 released.

Enjoy!

-- Ivan

**Comment by sbortman** [comment]
I think we have a winner!   Thanks again.
