### ISSUE TITLE
spring-security-rest plugin, 405 Method Not Allowed

### ISSUE THREAD

**Issue by pangeaos** [appcela/grails3-cors-interceptor#3]
I got this msg 405 Method Not Allowed on /api/login OPTIONS request with grails-spring-security-rest plugin.

Any idea how to use your plugin with that security plugin?

**Comment by ichangxappcela** [comment]
@barcelona23 It's a bug in the grails-spring-security-rest plugin, see [Add CORS support for plugin version 2.x #256](https://github.com/alvarosanchez/grails-spring-security-rest/issues/256) for bug details.

I've added a SpringSecurityCorsFilter to fix this problem. Please checkout the sample app [grails3-cors-interceptor-spring-security-rest-sample-app](https://github.com/appcela/grails3-cors-interceptor-spring-security-rest-sample-app) for detailed instructions.
- [Working with Spring Security REST Plugin](https://github.com/appcela/grails3-cors-interceptor-spring-security-rest-sample-app#working-with-spring-security-rest-plugin)

**Comment by pangeaos** [comment]
I had checked your example. the login(spring-security-rest) works great. thanks you!
but I'm getting this 'the 'access-control-allow-origin' header contains multiple values but only one is allowed' when I tried to make another request. ex. return $http.get('http://localhost:8080/me'); (AngularJS)

Any idea?

**Comment by ichangxappcela** [comment]
Oops! looks like I have missed an important Spring Security Core custom filter configuration, which has caused the duplicate CORS response headers issue. 

Just update your Spring config like this and you should be all set.

_conf/spring/resources.groovy_

```
import grails3.cors.interceptor.SpringSecurityCorsFilter

beans = {
    securityCorsFilter(SpringSecurityCorsFilter)

    // IMPORTANT! - add this to your Spring config
    myFilterDeregistrationBean(FilterRegistrationBean) {
        filter = ref('securityCorsFilter')
        enabled = false
    }
}
```

This is not a bug in the `grails3-cors-interceptor` code, just a configuration misstep in the [grails3-cors-interceptor-spring-security-rest-sample-app](https://github.com/appcela/grails3-cors-interceptor-spring-security-rest-sample-app).

For more info, please check out the latest [grails3-cors-interceptor-spring-security-rest-sample-app](https://github.com/appcela/grails3-cors-interceptor-spring-security-rest-sample-app).

**Comment by pangeaos** [comment]
it's working as aspected. Thank You. Good Work @appcela !

**Comment by orubel** [comment]
This was hard to find. Can you change label for this as 'duplicate headers' or add to README.md???

**Comment by orubel** [comment]
There is also [a nice little bit here](https://github.com/grails-plugins/grails-spring-security-core/blob/7f09c528bedcf53ff9d109dad725d68a54d36a2e/src/docs/filters.adoc) saying this has to be added to bootstrap as well to add the filter:

class BootStrap {

   def init = {
      SpringSecurityUtils.clientRegisterFilter(
          'myFilter', SecurityFilterPosition.OPENID_FILTER.order + 10)
   }
}
