### ISSUE TITLE
UrlMappings created by resr api profile

### ISSUE THREAD

**Issue by norricorp** [appcela/grails3-cors-interceptor#4]
Hi,
I created my grails 3 application using the rest api profile so the URL mappings were auto created. So I have entries such as 
        get "/$controller(.$format)?"(action:"index")
        get "/$controller/$id(.$format)?"(action:"show")
In this case, do I do something like
       get "/$controller/$id(.$format)?"(action:"show", method: "OPTIONS")
Regadrs,
John

**Comment by ichangxappcela** [comment]
No, for Grails 3.2.0, you no longer need to map the `OPTIONS` request manually. It should just work.
