### ISSUE TITLE
Configurable list of allowed headers

### ISSUE THREAD

**Issue by hbogaards** [appcela/grails3-cors-interceptor#6]
I would like to have the possibility to configure the list of allowed headers.

We have an API key header that we want to allow, but the list of allowed headers is hard-coded in `CorsService`

**Comment by joemccall86** [comment]
We have worked around the issue by having a secondary interceptor defined to add those headers. It is configured to run before the corsInterceptor because the corsInterceptor will return false and block other interceptors from running.

**Comment by ichangxappcela** [comment]
Added custom headers support in v1.2.0.

_application.yml_

```
corsInterceptor:
    ...
    allowedHeaders: ['my-authorization-header', 'origin', 'content-type', 'accept']
```
- allowedHeaders - custom headers to be used in "Access-Control-Allow-Headers" (default to `["origin", "authorization", "accept", "content-type", "x-requested-with"]`)
